### ISSUE TITLE
GitHub actions do not reflect the correct CI steps. Investigation needed

### ISSUE THREAD

**Issue by nmiodice** [terraform-providers/terraform-provider-azuredevops#10]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Issue
The GH Actions CI is not updated to use the make commands. But also, we are not seeing any CI reported through any other CI process. This makes it difficult to validate any changes

**Comment by nmiodice** [comment]
cc @cgriggs01 - I'd like to verify that the CI is hooked up on the backend. Can we add this check to the repo?

**Comment by cgriggs01** [comment]
👋 The TravisCI checks have been activated. Thanks for the nudge. 

Let me know if you need anything else?

**Comment by EliiseS** [comment]
@nmiodice @cgriggs01 The build ran on PR's is still running GithubActions not TravisCI, is that intended? Should we be updating the GithubActions file since it's broke right now?

**Comment by xuzhang3** [comment]
@cgriggs01 Where is the TravisCI checks configured. Can we setup PR checks in TravisCI?  Current PR check is use the ` .check-pr.yml`  in GitHub action which is outdated.
Relate issue : #19 
cc @tmeckel

**Comment by xuzhang3** [comment]
Closing this issue due to #24
