### ISSUE TITLE
Failure Creating Repo + CI 

### ISSUE THREAD

**Issue by lfmundim** [terraform-providers/terraform-provider-azuredevops#15]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```
Terraform v0.12.26
+ provider.azuredevops v0.0.1
```

### Affected Resource(s)

* azuredevops_build_definition`

### Terraform Configuration Files

```hcl
provider "azuredevops" {
  version = ">= 0.0.1"
}

resource "azuredevops_git_repository" "repo" {
  project_id = "some-guid"
  name       = "some-name"
}

resource "azuredevops_build_definition" "build" {
  project_id = "some-guid"
  name       = "some-name - CI"
 
  repository {
    repo_type   = "TfsGit"
    repo_id   = azuredevops_git_repository.repo.id
    branch_name = azuredevops_git_repository.repo.default_branch
    yml_path    = "azure-pipelines.yml"
  }
}
```
### Debug Output

https://gist.github.com/lfmundim/8083ce0abadb4567545e33ace29ba4bf

### Panic Output

https://gist.github.com/lfmundim/7658419c40c4607ae88ff459da79f6c0

### Expected Behavior

New repo and CI should have been created
### Actual Behavior

New repo was created
### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Important Factoids

Following (partly) [the article](https://cloudblogs.microsoft.com/opensource/2020/06/18/announcing-hashicorp-terraform-azure-devops-provider-release/) that marked the release of v0.0.1 of the AZDO provider, along with the official [reference](https://www.terraform.io/docs/providers/azuredevops/r/build_definition.html). The `.tf` works fine without the `azuredevops_build_definition` section

**Comment by xuzhang3** [comment]
Close this issue for #92 . If you still have question, feel free to reopen it.
