### ISSUE TITLE
Resource Authorization Missing Navigation

### ISSUE THREAD

**Issue by straubt1** [terraform-providers/terraform-provider-azuredevops#3]
### Documentation issue

The resource `azuredevops_resource_authorization` documentation page has broken navigation.

### Terraform (and Azure DevOps Provider) Version

n/a

### Affected Resource(s)

* `azuredevops_resource_authorization`

### References

* [azuredevops_resource_authorization direct link](https://www.terraform.io/docs/providers/azuredevops/r/resource_authorization.html)

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/8408833/85229150-d86da580-b3ad-11ea-9fec-422462446385.png">

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by EliiseS** [comment]
@straubt1 When are the pages updated based on the code? I've added the fix to master, but the pages on terraform are still broken atm

**Comment by straubt1** [comment]
@EliiseS I believe website changes are only pushed during a provider release, but let me verify.

**Comment by straubt1** [comment]
I can confirm, the easiest way is to release the provider to update the docs.
