### ISSUE TITLE
Create Fork with azuredevops_git_repository parent_id not working

### ISSUE THREAD

**Issue by EliiseS** [terraform-providers/terraform-provider-azuredevops#36]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/377
Originally created by @jakobyte1024 on *Thu, 25 Jun 2020 15:12:12 GMT*

---

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version
* provider.azuredevops: version = "~> 0.0"
* provider.azurerm: version = "~> 2.15"
Terraform v0.12.27

### Affected Resource(s)

* `azuredevops_git_repository`

### Terraform Configuration Files

```hcl
data "azuredevops_project" "jakobyte1024AdoProject" {
  project_name = "jakobyte1024"
}

data "azuredevops_git_repositories" "jakobyte1024SkeletonRepo" {
  project_id = data.azuredevops_project.jakobyte1024AdoProject.id
  name       = "RepoSkeleton"
}

resource "azuredevops_git_repository" "SkeletonFork" {
  project_id = azuredevops_project.tenantAdoProject.id
  name       = "SkeletonFork"
  parent_id  = azuredevops_git_repositories.jakobyte1024SkeletonRepo.id
}
```

### Debug Output
[https://gist.github.com/jakobyte1024/5c295583599a0b976bab65a2d7500ca7](https://gist.github.com/jakobyte1024/5c295583599a0b976bab65a2d7500ca7)

### Expected Behavior

Dear AzureDevOps Provider Team,
I may run into an issue. While creating a fork repo, parent_id seems not to be supported.
But the documentation tells me that I should use it like in above's snippet.
Am I doing something wrong or impossible ?
Or did I find a bug ?
In any case - thank you for any help.

The parent repo in another project is being looked up.
And a new repo in a new project has been created

### Actual Behavior

Instead of, project_id seems not to be supported.
Also tested with azuredevops_git_repository instead of data azuredevops_git_repositories

### Steps to Reproduce

1. `terraform apply`

* #0000

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/377#issuecomment-651099264
Originally created by @muellermatthias on *Mon, 29 Jun 2020 12:52:22 GMT*

---
I ran into the same problem.
After checking the code I found the option `parent_repository_id`.
Using that will result in a terraform crash: `panic: runtime error: invalid memory address or nil pointer dereference`, but will fork the repo successfully at the same time.

Terraform v0.12.13
+ provider.azuredevops v0.0.1

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/377#issuecomment-651978415
Originally created by @cd83 on *Tue, 30 Jun 2020 18:50:23 GMT*

---
Terraform v0.12.24

I can confirm that using `parent_repository_id` works as @muellermatthias stated. However, Terraform does not crash in my case and instead I get the following error message:

```
azuredevops_git_repository.repo: Creating...

Error: Error expanding repository resource data: Initialization strategy not implemented: Import

  on main.tf line 50, in resource "azuredevops_git_repository" "repo":
  50: resource "azuredevops_git_repository" "repo" {
```

**Comment by xuzhang3** [comment]
Close this issue for #55
