### ISSUE TITLE
Implement Terrafrom resource azuredevops_git_permissions

### ISSUE THREAD

**Issue by EliiseS** [terraform-providers/terraform-provider-azuredevops#46]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/153
Originally created by @tmeckel on *Fri, 25 Oct 2019 12:17:24 GMT*

---

## Community Note

* Please vote on this issue by adding a 👍
  [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this
  request
* Please do not leave "+1" or "me too" comments, they generate extra noise for
  issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

## Description

As a developer, I want the ability to manage the permissions of all Git
repositories inside a project, a single Git Repository and a single branch
inside a Git repository in Azure DevOps. Thus a new Terraform resource shall be
provided.

The resource shall provide three attributes to define the scope on which the
permissions should be applied:

* `project_id` (required)
* `repository_id` (optional)
* `branch_id` (optional)

Logic:

1. to apply permissions to all Git repositories inside a project set `project_id`
2. to apply permissions to a specific Git repository inside a project set `project_id` and `repository_id`
3. to apply permissions to a branch inside a Git repository of a project set `project_id`, `repository_id` and `branch_id`

The resource shall issue an error if:

1. the `project_id` is not set
2. the `branch_id` is set without having set `repository_id`

### New or Affected Resource(s)

* azuredevops_git_permissions

### Potential Terraform Configuration

```hcl

data "azuredevops_project" "project" {
   # Exports: id
   project_name = "Test Project"
}

resource "azuredevops_group" "project-group" {
    # Exports: id, descriptor (Security Descriptor)
    project_id = data.azuredevops_project.project.id
    name       = "Test Group"
}

data "azuredevops_git_repository" "repo" {
    name = "RepoV2"
}

data "azuredevops_git_branch" "branch_foobar" {
    name          = "Foobar"
    repository_id = data.azuredevops_git_repository.repo.id
    # Id            = /refs/heads/6d0061007300740065007200
}

resource "azuredevops_git_permissions" "perm" {
    # Security Namespace: 2e9eb7ed-3c0a-47d4-87c1-0ffdd275fd87

    // Build ACL token from project id (GUID) as follows
    // repoV2/<projectGUID>/<repoGUID>/<branchGUID>
    project_id    = data.azuredevops_project.project.id
    repository_id = data.azuredevops_git_repository.repo.id
    branch_id     = data.azuredevops_git_branch.branch_foobar.id

    principals = [
        data.azuredevops_project_user.lookup-project-user.id_descriptor
        azuredevops_user.project-user.id_descriptor
        # id_descriptor returns the decoded descriptor value (identity descriptor)
        # id => aad.YmZhYmE4ZDUtZWMzZC03ZjIzLWE4NDktMDM3ZjEwMTEwNDZh
        # id_descriptor => Microsoft.IdentityModel.Claims.ClaimsIdentity;2eb07b91-f9f8-437b-a89e-59f55e565c11\\EE03B31@UNION-INVESTMENT.DE
        azuredevops_group.project-group.id_descriptor
    ]

    permissions = {
        "Administer"   = "Allow"
        "ForcePush"    = "Deny"
        "CreateBranch" = "NotSet"
    }

}

```

### Acceptance Criteria

[] Include Unit tests for the new operation 

[] Acceptance (integration) test to validate repo creation/modification, 
   following the patterns from the azuredevops_build_definition resource

### References

* #0000

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/153#issuecomment-546466642
Originally created by @tmeckel on *Fri, 25 Oct 2019 18:41:10 GMT*

---
@nmiodice same comment about security namespaces and their ACE list as in #104

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/153#issuecomment-546468930
Originally created by @tmeckel on *Fri, 25 Oct 2019 18:47:43 GMT*

---
Copy @tiwood as reference

**Comment by EliiseS** [comment]
---

Migrated from https://github.com/microsoft/terraform-provider-azuredevops/issues/153#issuecomment-546403169
Originally created by @nmiodice on *Fri, 25 Oct 2019 15:36:01 GMT*

---
Similar comment to https://github.com/microsoft/terraform-provider-azuredevops/issues/104 regarding removing the `principals` block

**Comment by EliiseS** [comment]
@tmeckel Can you comment on this issue so I can assign you back?

**Comment by tmeckel** [comment]
> 
> 
> @tmeckel Can you comment on this issue so I can assign you back?
> 
> Context: [isaacs/github#100 (comment)](https://github.com/isaacs/github/issues/100#issuecomment-505564361)

🥇
