### ISSUE TITLE
Project Creation - Ability to NOT create the default repository.

### ISSUE THREAD

**Issue by straubt1** [terraform-providers/terraform-provider-azuredevops#5]
### Description

When creating a new Azure DevOps project, a default git repository is created with the same name.

It would be ideal if the `azuredevops_project` exposed an option to either not created this repository, or delete it automatically in the backend.

### New or Affected Resource(s)

* azuredevops_project

### Potential Terraform Configuration

azuredevops_project

```hcl
resource "azuredevops_project" "project" {
  project_name       = "Test Project"
  ...

  create_default_repository = false

}
```

### References

* [azuredevops_project](https://www.terraform.io/docs/providers/azuredevops/r/project.html)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by nmiodice** [comment]
I've previously done a pretty big deep dive into this and found the following limitations to the way Azure DevOps works in general. There are two challenges, which make me think that this is impossible to fix in a clean, generic way:

- The API for creating projects does not allow you to create a project without a repository. So we'd have to create the project, and then delete the repo. However...
- Azure DevOps will not allow you to delete a repository if it is the only one in the project.
![image](https://user-images.githubusercontent.com/2497673/85312906-184f8e00-b47d-11ea-9843-7c2c7064e234.png)


Based on this, I don't believe it to be possible to achieve the ask in this issue, though I do wish for this behavior all the time :/

**Comment by straubt1** [comment]
I see, that is not ideal and understand the conundrum.

Interesting choice for ADO given you can use GitHub as your repo source 🤔 

Many thanks, I agree there isn't much the ADO Provider can do here.

**Comment by EliiseS** [comment]
@straubt1 Should we close this? :)

**Comment by straubt1** [comment]
I am good with that, we can't fix this in this provider :)
